=== juandmelendezpe/Daw-LM/UT3-LM/C3_dtd/ExpedienteAcademico.dtd
<!ELEMENT expedientes (expediente+)>
<!ELEMENT expediente (titulacion,estudiante,modulos)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT estudiante (#PCDATA)>
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo EMPTY >

<!ATTLIST modulo nombre CDATA #REQUIRED>
<!ATTLIST modulo aprobado (true|false) #REQUIRED>
<!ATTLIST modulo curso (Primero|segundo) #REQUIRED>
<!ATTLIST expedientes noNamespaceSchemaLocation CDATA #REQUIRED>

=== juandmelendezpe/Daw-LM/UT3-LM/C3_dtd/ExpedienteAcademico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE expedientes SYSTEM "./ExpedienteAcademico.dtd" >
<!--<expedientes noNamespeceSchemalocation="./ExpedienteAcademico.xsd" >-->
<expedientes>
    <expediente>
        <titulacion>DAM</titulacion>
        <estudiante>Ainhoa Gárate</estudiante>
        <modulos>
            <modulo nombre="Sistemas" aprobado="true" curso="Primero"/>
            <modulo nombre="Lenguaje de Marcas" aprobado="true" curso="Primero"/>
            <modulo nombre="Programación multmedia" aprobado="false" curso="Segundo"/>
        </modulos>
    </expediente>
    <expediente>
        <titulacion>DAW</titulacion>
        <estudiante>Ferran Soler</estudiante>
        <modulos>
            <modulo nombre="Programación" aprobado="true" curso="Primero"/>
            <modulo nombre="Desarrollo web en cliente" aprobado="false" curso="Segundo"/>
            <modulo nombre="Desarrollo web en servidor" aprobado="false" curso="Segundo"/>
        </modulos>
    </expediente>
</expedientes>
