=== juandmelendezpe/Daw-LM/UT3-LM/C3_dtd/libros.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="biblioteca">
 <xs:complexType>
    <xs:sequence>
        <xs:element name="editorial" maxOccurs="unbounded" ></xs:element>
        <xs:element name="email">
            <xs:complexType>
                <xs:sequence>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="email">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:attribute name="tipo" use="optional">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[A-Za-z0-9._]*@[A-Za-z0-9.-]*.[A-Za-z]{2,3}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:simpleContent>
                            </xs:complexType>
                    </xs:sequence>
                </xs:sequence>
            </xs:complexType>

        </xs:element>


    </xs:sequence>

 </xs:complexType>
    

 </xs:element>
 </xs:schema>

=== juandmelendezpe/Daw-LM/UT3-LM/C3_dtd/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (editorial+)>
<!ELEMENT editorial (nombre,email)>
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT email (#PCDATA) > 
<!ATTLIST email tipo (corporativo|personal) >
<!ATTLIST biblioteca noNamespaceSchemaLocation CDATA #REQUIRED>
]
 >
<biblioteca noNamespaceSchemaLocation="libros.xsd">
    <editorial>
        <nombre>Editorial IA</nombre>
        <email tipo ="corporativo">john@gnmail.com</email>
    </editorial>
     <editorial>
        <nombre>Editorial advance</nombre>
        <email tipo ="personal"> jane@gmail.com</email>
    </editorial>
    <editorial>
        <nombre>Editorial IA</nombre>
        <email >byby@gmail.com</email> 
    </editorial>
</biblioteca>
