=== juandmelendezpe/Daw-LM/UT3-LM/C3_dtd/listin.dtd
<!ELEMENT listin (persona+)>
<!ELEMENT persona (nombre,(email| telefono)+,relacion?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA) >
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT relacion EMPTY>
<!ATTLIST persona edad CDATA #IMPLIED>
<!ATTLIST persona sexo (hombre|mujer) #REQUIRED>
<!ATTLIST persona id ID #REQUIRED >
<!ATTLIST relacion amigo-de IDREFS #IMPLIED>
<!ATTLIST relacion enemigo-de IDREFS #IMPLIED>

=== juandmelendezpe/Daw-LM/UT3-LM/C3_dtd/listin.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE listin SYSTEM "./listin.dtd">
<listin>
    <persona edad="48" sexo="hombre" id="ricky">
        <nombre>RIKCI MARTYIN</nombre>
        <email>AJFKJASDLKF@KDJFKLAJKSDL.COM</email>
        <relacion amigo-de="leti"/>
    </persona>
    <persona sexo="mujer" id="leti">
        <nombre>Leticia Casta</nombre>
        <email>castal@micasa.com</email>
    </persona>
    <persona sexo="mujer" id="bea">
        <nombre>Bea la Santa</nombre>
        <email>bea@micasa.com</email>
        <telefono>948858562</telefono>
        <relacion enemigo-de="ricky"/>
    </persona>
</listin>
