=== juandmelendezpe/Daw-LM/UT3-LM/C3_dtd/persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="mayor_de_edad" type="xs:string" minOccurs="0"/>
                            <xs:element name="ciudad" type="xs:string"/>
                            <xs:element name="rol" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="dni" type="xs:string"/>
                        <xs:attribute name="formapago" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juandmelendezpe/Daw-LM/UT3-LM/C3_dtd/persona.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="./persona.xsd">
    <persona dni="123123">
        <nombre>Andrea Solís</nombre>
        <mayor_de_edad />
        <ciudad>Córdoba</ciudad>
        <rol> cliente </rol>
    </persona>
    <persona dni="234234" formapago="Tarjeta">
        <nombre>Dora la exploradora</nombre>
        <ciudad>Córdoba</ciudad>
       <rol> cliente </rol>
    </persona>
    </personas>
